project:
  type: book
  output-dir: docs

book:
  title: "Exploring the Social World - Quantitative Block: Statistics"
  author: "Gabriele Filomena and Zi Ye"
  date: today

  page-footer:
    left: |
     Exploring the Social World - Quantitative Block: Statistics by Gabriele Filomena and Zi Ye.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  search: true
  site-url:  https://gdsl-ul.github.io/stats
  repo-url: https://github.com/GDSL-UL/stats
  repo-actions: [edit]
  sidebar:
    style: docked
    background: light
  downloads: [pdf]
  chapters:
    - index.qmd
    - general/overview.qmd
    - general/assessment.qmd
    - general/howSubmit.qmd
    - general/reportTemplate.qmd
    - general/wdPaths.qmd
    - labs/00.introR.qmd
    - labs/01.DataExploration.qmd
    - labs/02.MultipleLinear.qmd
    # - labs/03.QualitativeVariable.qmd
    # - labs/04.LogisticRegression.qmd
    # - labs/05.Visualisation.qmd
    # - labs/06.Summary.qmd

bibliography: references.bib

format:
  html:
    theme: zephyr
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual



