# Assessment: How to submit {.unnumbered}

Normally you don't need to do so, but if something does not work, you may have to install [Quarto](https://quarto.org). Recent versions of RStudio do not require you to do so.

## .html file

**Submit a single, self-contained `.html` file. PDF submissions are not accepted.**

The `.html` file is a rendered version of a Quarto Markdown file (`qmd` file). This will allow you to write a research paper that also includes your working code, without the need of including the data (the code in a `.qmd` file is executed before the document is converted to HTML).

To do so, at the top of your document, include something like this in a YAML cell (see [Template](reportTemplate.qmd), in RStudio, "visual view", `Insert`, `YAML block`)

```         
---
title: "ENVS225 Assignment"
author: "Anonymous" # do not change
format:
  html:
    self-contained: true
---
```

Once your document is ready with your text and code, render the Quarto document: Click the **Render** button in the RStudio toolbar (blue arrow). This, if everything works (code, existing data, etc), will create an `.html` file in the same location as your `.qmd` file
