<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zi Ye">
<meta name="dcterms.date" content="2026-09-25">

<title>4&nbsp; Lab: Correlation and Multiple Linear Regression with Qualitative Variables – Exploring the Social World - Quantitative Block: Statistics</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../labs/04.LogisticRegression.html" rel="next">
<link href="../labs/02.MultipleLinear.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-0cc71461e62f88dea9cf8ae7d3dd06d7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../labs/03.QualitativeVariable.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab: Correlation and Multiple Linear Regression with Qualitative Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Exploring the Social World - Quantitative Block: Statistics</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/GDSL-UL/stats" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../Exploring-the-Social-World---Quantitative-Block--Statistics.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../general/overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../general/assessment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assessment</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../general/howSubmit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Assessment: How to submit</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../general/reportTemplate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ENVS225 Assignment 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../general/wdPaths.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Working Directories and Paths</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/00.introR.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Lab: Introduction to R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/01.DataExploration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lab: Exploring a Dataset</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/02.MultipleLinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lab: Correlation, Single, and Multiple Linear Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/03.QualitativeVariable.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab: Correlation and Multiple Linear Regression with Qualitative Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/04.LogisticRegression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Lab: Logistic Regression</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../labs/05.Visualisation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Lab: Data Visualisation with ggplot</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#analysing-categorical-variables" id="toc-analysing-categorical-variables" class="nav-link active" data-scroll-target="#analysing-categorical-variables"><span class="header-section-number">4.1</span> Analysing categorical variables</a>
  <ul>
  <li><a href="#data-overview" id="toc-data-overview" class="nav-link" data-scroll-target="#data-overview"><span class="header-section-number">4.1.1</span> Data overview</a></li>
  <li><a href="#correlation" id="toc-correlation" class="nav-link" data-scroll-target="#correlation"><span class="header-section-number">4.1.2</span> Correlation</a>
  <ul class="collapse">
  <li><a href="#q1-what-are-strongest-and-weakest-associations-health-status" id="toc-q1-what-are-strongest-and-weakest-associations-health-status" class="nav-link" data-scroll-target="#q1-what-are-strongest-and-weakest-associations-health-status">Q1: What are strongest and weakest associations health status?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#income-inequality-with-respect-to-gender-and-health-status" id="toc-income-inequality-with-respect-to-gender-and-health-status" class="nav-link" data-scroll-target="#income-inequality-with-respect-to-gender-and-health-status"><span class="header-section-number">4.2</span> Income inequality with respect to gender and health status</a>
  <ul>
  <li><a href="#q2.-income-inequality-by-gender-and-health" id="toc-q2.-income-inequality-by-gender-and-health" class="nav-link" data-scroll-target="#q2.-income-inequality-by-gender-and-health">Q2. Income inequality by gender and health</a></li>
  </ul></li>
  <li><a href="#implementing-a-linear-regression-model-with-a-qualitative-independent-variable" id="toc-implementing-a-linear-regression-model-with-a-qualitative-independent-variable" class="nav-link" data-scroll-target="#implementing-a-linear-regression-model-with-a-qualitative-independent-variable"><span class="header-section-number">4.3</span> <strong>Implementing a linear regression model with a qualitative independent variable</strong></a>
  <ul>
  <li><a href="#q3.-categories-of-region" id="toc-q3.-categories-of-region" class="nav-link" data-scroll-target="#q3.-categories-of-region">Q3. Categories of Region</a></li>
  <li><a href="#include-the-categorical-variables-into-a-regression-model" id="toc-include-the-categorical-variables-into-a-regression-model" class="nav-link" data-scroll-target="#include-the-categorical-variables-into-a-regression-model"><span class="header-section-number">4.3.1</span> <strong>Include the categorical variables into a regression model</strong></a>
  <ul class="collapse">
  <li><a href="#q4.-regional-differences-compared-with-london" id="toc-q4.-regional-differences-compared-with-london" class="nav-link" data-scroll-target="#q4.-regional-differences-compared-with-london">Q4. Regional differences compared with London</a></li>
  </ul></li>
  <li><a href="#change-the-baseline-category" id="toc-change-the-baseline-category" class="nav-link" data-scroll-target="#change-the-baseline-category"><span class="header-section-number">4.3.2</span> <strong>Change the baseline category</strong></a></li>
  <li><a href="#recode-the-region-variable-and-explore-regional-inequality-in-health" id="toc-recode-the-region-variable-and-explore-regional-inequality-in-health" class="nav-link" data-scroll-target="#recode-the-region-variable-and-explore-regional-inequality-in-health"><span class="header-section-number">4.3.3</span> Recode the Region variable and explore regional inequality in health</a>
  <ul class="collapse">
  <li><a href="#q5.-london-vs-north-and-south-vs-wales" id="toc-q5.-london-vs-north-and-south-vs-wales" class="nav-link" data-scroll-target="#q5.-london-vs-north-and-south-vs-wales">Q5. London vs North, and South vs Wales</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#predictions-using-fitted-regression-model" id="toc-predictions-using-fitted-regression-model" class="nav-link" data-scroll-target="#predictions-using-fitted-regression-model"><span class="header-section-number">4.4</span> Predictions using fitted regression model</a>
  <ul>
  <li><a href="#q6.-predicting-long-term-illness-in-wales-and-london" id="toc-q6.-predicting-long-term-illness-in-wales-and-london" class="nav-link" data-scroll-target="#q6.-predicting-long-term-illness-in-wales-and-london">Q6. Predicting long-term illness in Wales and London</a></li>
  </ul></li>
  <li><a href="#answers-to-the-questions" id="toc-answers-to-the-questions" class="nav-link" data-scroll-target="#answers-to-the-questions"><span class="header-section-number">4.5</span> <strong>Answers to the Questions</strong></a>
  <ul>
  <li><a href="#q1-associations-with-health-status" id="toc-q1-associations-with-health-status" class="nav-link" data-scroll-target="#q1-associations-with-health-status"><span class="header-section-number">4.5.1</span> Q1 associations with health status</a></li>
  <li><a href="#q2-income-inequality-by-gender-and-health-status" id="toc-q2-income-inequality-by-gender-and-health-status" class="nav-link" data-scroll-target="#q2-income-inequality-by-gender-and-health-status"><span class="header-section-number">4.5.2</span> Q2: income inequality by gender and health status</a></li>
  <li><a href="#q3-categories-of-region" id="toc-q3-categories-of-region" class="nav-link" data-scroll-target="#q3-categories-of-region"><span class="header-section-number">4.5.3</span> Q3: categories of Region</a></li>
  <li><a href="#q4-regions-that-differ-significantly-from-london" id="toc-q4-regions-that-differ-significantly-from-london" class="nav-link" data-scroll-target="#q4-regions-that-differ-significantly-from-london"><span class="header-section-number">4.5.4</span> Q4: regions that differ significantly from London</a></li>
  <li><a href="#changing-the-baseline-to-north-west" id="toc-changing-the-baseline-to-north-west" class="nav-link" data-scroll-target="#changing-the-baseline-to-north-west"><span class="header-section-number">4.5.5</span> Changing the baseline to North West</a></li>
  <li><a href="#q5-london-vs-north-and-south-vs-wales" id="toc-q5-london-vs-north-and-south-vs-wales" class="nav-link" data-scroll-target="#q5-london-vs-north-and-south-vs-wales"><span class="header-section-number">4.5.6</span> Q5: London vs North, and South vs Wales</a></li>
  <li><a href="#the-written-down-model-and-q6" id="toc-the-written-down-model-and-q6" class="nav-link" data-scroll-target="#the-written-down-model-and-q6"><span class="header-section-number">4.5.7</span> The written-down model and Q6</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/GDSL-UL/stats/edit/main/labs/03.QualitativeVariable.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Lab: Correlation and Multiple Linear Regression with Qualitative Variables</span></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Zi Ye </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>The lecture’s slides can be found&nbsp;<a href="https://github.com/GDSL-UL/stats/blob/main/lectures/lecture03.pdf">here</a>.</p>
<p>Last week, we introduced Multiple Linear Regression (MLR) - a statistical method that models the relationship between a dependent variable and two or more independent variables, allowing researchers to examine how various predictors jointly influence an outcome. By using the following R code, we create and interpret the model:</p>
<p><code>model &lt;- lm(pct_Very_bad_health ~ pct_No_qualifications + pct_Males + pct_Higher_manager_prof, data = census)</code></p>
<p><code>summary(model)</code></p>
<p>In a regression model, independent/predictor variables could be continuous or categorical (or qualitative). While continuous variables capture quantitative effects, <strong>categorical variables provide insights into differences across groups</strong>. When we say categorical variables, we normally mean:</p>
<ul>
<li><p>Nominal Data: categorical data without natural order. E.g. Gender, Colour, Country…</p></li>
<li><p>Ordinal Data: categorical data with a meaningful order. E.g. Education level, Customer satisfaction, Grade…</p></li>
</ul>
<p>By blending continuous and categorical predictors, MLR with categorical variables enhances the model’s ability to reflect real-world complexities and improves interpretability, as it allows analysts to assess how each category or group within an independent variable influences the dependent variable.</p>
<p>For most categorical (especially the <em>nominal</em>) variables, they cannot be included in the regression model directly as a continuous independent variable. Instead, these qualitative independent variables should be included in regression models by using the <strong>dummy variable</strong> approach, transforming categorical information into a numerical format suitable for regression analysis.</p>
<p>However, R provides a powerful way, by automatively handling this process when the categorical variable is designated as a factor and to be included in the regression model. This makes it much easier for you to use categorical variables in the regression model to assess the effects of categorical groupings on the dependent variable alongside continuous predictors.</p>
<p>Learning Objectives:</p>
<p>In this week’s practical we are going to</p>
<ul>
<li><p>Analysis of categorical/qualitative variables</p></li>
<li><p>Estimate and interpret a multiple linear regression model with categorical variables</p></li>
<li><p>Make predictions using a regression model</p></li>
</ul>
<section id="analysing-categorical-variables" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="analysing-categorical-variables"><span class="header-section-number">4.1</span> Analysing categorical variables</h2>
<p>Recall in Week 2, you got familiar with R by using the Census data. Today we will explore both the Family Resource Survey (FRS) and the Census data by using their categorical variables. You should already have your Census data in your local drive folder under the path of ‘/data/Census2021/’; for the FRS datasets, please click the links to download the datasets from <a href="https://canvas.liverpool.ac.uk/courses/84668/pages/family-resource-survey-2016-17?module_item_id=2396198">Canvas</a>. Please download both the datasets of ‘FRS16-17_labels.csv’ and ‘FRS_dictionary.xlxs’<!--and 'FRS16-17_codes.csv'--> for today’s practical. You may create a new folder named ‘FRS’ under the ‘/data/’ along with the Census2021 folder, and put the newly downloaded .csv files at the ‘/data/FRS/’ folder for later use.</p>
<!--Now, there should be two .csv file: 'FRS16-17_labels.csv' and 'FRS16-17_codes.csv' in your '/data/FRS' folder. Double click to open both .csv files you may find they have exactly same column names - yes, they are in fact the same spreadsheet but 'FRS16-17_labels.csv' is more readable for the cell contents as they are in text format but cells 'FRS16-17_codes.csv' is in coding format. This is quite normal as when we doing surveys, we use text as the options of multiple choice questions for respondents to choose from, and therefore the collected survey results are in the 'FRS16-17_labels.csv' format. For example, for the multiple choice question - which region you are from? The options include 'London', 'North West', 'Wales', etc. However, while analysing the survey results, these text content (the options of multiple choice questions) are in fact different categories of the categorical/qualitative variable. So for some survey results, you may find they are formatted in coding way as 'FRS16-17_codes.csv', and along with a coding dictionary for you to learn the meaning of each coding. -->
<p>To start today’s practical session, we first will use ‘FRS16-17_labels.csv’. <!--In the Region example, there are 12 categories for the categorical/qualitative variable Region--> You can open the .csv file in Excel and find its different from the Census dataset, the FRS dataset contains many qualitative/categorical variables, such as hh_tenure (Housing Tenure), happy (How happy did you feel yesterday?), health (How is your health in general) and etc. To know the meaning of all the column names and the values in cell, you may need to reference to the ‘FRS_dictionary.xlsx’ to help your understanding. Recall our lecture, these categorical variable will need to be treated as Dummy variable in the regression model. In R, the variable type of qualitative/categorical variables is called ‘<strong>factor</strong>’.</p>
<p>As usual we first load the necessary libraries.</p>
<p><strong>Some tips to avoid R returning can’t find data errors:</strong></p>
<p>Check your working directory by</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Check the relative path of your data folder on your PC/laptop, make sure you know the relative path of your data from your working directory, returned by <code>getwd()</code>.</p>
<p><strong>Library knowledge used today:</strong></p>
<ul>
<li><p><strong><code>dplyr</code></strong>: a basic library provides a suite of functions for data manipulation</p></li>
<li><p><strong><code>ggplot2</code></strong>: a widely-used data visualisation library to help you create nice plots through layered plotting.</p></li>
<li><p><strong><code>tidyverse</code></strong>: a collection of R packages designed for data science, offering a cohesive framework for data manipulation, visualization, and analysis. Containing dplyr, ggplot2 and other basic libraries.</p></li>
<li><p><strong><code>broom</code></strong>: a part of the tidyverse and is designed to convert statistical analysis results into tidy data frames.</p></li>
<li><p><strong><code>forcats</code></strong>: designed to work with factors, which are used to represent categorical data. It simplifies the process of creating, modifying, and ordering factors.</p></li>
<li><p><strong><code>vcd</code></strong>: visualise and analyse categorical data.</p></li>
</ul>
<p><strong>A useful shortcut to format your code: select all your code lines, use Ctrl+Shift+A for automatically format them in a tidy way.</strong></p>
<section id="data-overview" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="data-overview"><span class="header-section-number">4.1.1</span> Data overview</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"dplyr"</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"dplyr"</span>,<span class="at">dependencies =</span> T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: dplyr</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary libraries </span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"ggplot2"</span>))</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>,<span class="at">dependencies =</span> T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: ggplot2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"broom"</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"broom"</span>,<span class="at">dependencies =</span> T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: broom</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Or we can use library <code>tidyverse</code> which includes <code>ggplot2</code>, <code>dplyr,broom</code> and other fundamental libraries together already, remember you need first install the package if you haven’t by using <code>install.packages("tidyverse")</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"tidyverse"</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>,<span class="at">dependencies =</span> T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: tidyverse</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ stringr   1.5.2
✔ lubridate 1.9.4     ✔ tibble    3.3.0
✔ purrr     1.1.0     ✔ tidyr     1.3.1
✔ readr     2.1.5     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>We will also use ‘forcats’ library, so</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"forcats"</span>))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">install.packages</span>(<span class="st">"forcats"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(forcats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Exactly as you did in previous weeks, we first load in the dataset:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>frs_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/FRS/FRS16-17_labels.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Recall in previous weeks, we used the following code to overview the dataset. Familiarise yourself again by using them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(frs_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>and also <code>summary()</code> to produce summaries of each variable</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(frs_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You may notice that for the numeric variables such as <em>hh_income_gross</em> (household gross income) and <em>work_hours</em>(worked hours per week), the <code>summary()</code> offers useful descriptive statistics. While for the qualitative information, such as <em>age_group</em> (age group), <em>highest_qual</em> (Highest educational qualification), <em>marital_status</em> (Marital status) and <em>nssec</em> (Socio-economic status), the <code>summary()</code> function is not that useful by providing mean or median values.</p>
<p>Performing descriptive analysis for categorical variables or qualitative variables, we focus on summarising the frequency and distribution of categories within the variable. This analysis helps understand the composition and diversity of categories in the data, which is especially useful for identifying patterns, common categories, or potential data imbalances.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequency count</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_data<span class="sc">$</span>age_group)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  0-4 05-10 11-15 16-19 20-24 25-29 30-34 35-39 40-44 45-49 50-54 55-59 60-64 
 2914  3575  2599  1858  1929  2353  2800  2840  2790  2883  2975  2767  2775 
65-69 70-74   75+ 
 2990  2354  3743 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_data<span class="sc">$</span>highest_qual)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
A-level or equivalent       Degree or above       Dependent child 
                 5260                  9156                 10298 
   GCSE or equivalent             Not known                 Other 
                 9729                  6820                  2882 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_data<span class="sc">$</span>marital_status)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                          Cohabiting Divorced/civil partnership dissolved 
                                4015                                 2199 
           Married/Civil partnership                            Separated 
                               18195                                  747 
                              Single                              Widowed 
                               16663                                 2326 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_data<span class="sc">$</span>nssec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                              Dependent child 
                                        10299 
                            Full-time student 
                                          963 
              Higher professional occupations 
                                         3004 
                     Intermediate occupations 
                                         4372 
          Large employers and higher managers 
                                         1025 
Lower managerial and professional occupations 
                                         8129 
  Lower supervisory and technical occupations 
                                         2400 
         Never worked or long-term unemployed 
                                         1516 
                             Not classifiable 
                                          107 
                          Routine occupations 
                                         4205 
                     Semi-routine occupations 
                                         5226 
      Small employers and own account workers 
                                         2899 </code></pre>
</div>
</div>
<p>By using ggplot2, it is easy to create some nice descriptive charts for the categorical variables, just like what you did for the continuous variables last week.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(frs_data, <span class="fu">aes</span>(<span class="at">x =</span> highest_qual)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">"brown"</span>,<span class="at">width=</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Highest Qualification in FRS"</span>, <span class="at">x =</span> <span class="st">"Highest Qualification"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)<span class="sc">+</span><span class="co">#set text info</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="co">#choose theme type, try theme_bw(), theme_minimal() see differences</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03.QualitativeVariable_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(frs_data, <span class="fu">aes</span>(<span class="at">x =</span> health)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">"skyblue"</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="at">stat =</span> <span class="st">"count"</span>, <span class="fu">aes</span>(<span class="at">label =</span> ..count..),<span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.3</span>,<span class="at">colour =</span> <span class="st">"grey"</span>)<span class="sc">+</span> <span class="co">#add text</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Health in FRS"</span>, <span class="at">x =</span> <span class="st">"Health"</span>, <span class="at">y =</span> <span class="st">"Count"</span>)<span class="sc">+</span><span class="co">#set text info</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03.QualitativeVariable_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(frs_data, <span class="fu">aes</span>(<span class="at">x =</span> nssec)) <span class="sc">+</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"yellow4"</span>) <span class="sc">+</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of NSSEC in FRS"</span>, <span class="at">x =</span> <span class="st">"NSSEC"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span> <span class="co">#Flip the Axes, add a # in front of this line, to make the code in gray and you will see why we would better flip the axes at here</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03.QualitativeVariable_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>If we want to reorder the Y axis by from highest to lowest, we use the functions in <code>forcats</code> library. <code>fct_infreq()</code>: orders by the value’s frequency of the variable <code>nssec</code>. <code>fct_rev()</code>: reverses the order to go from highest to lowest.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(frs_data, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">fct_rev</span>(<span class="fu">fct_infreq</span>(nssec)))) <span class="sc">+</span> </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill =</span> <span class="st">"yellow4"</span>) <span class="sc">+</span> </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of NSSEC in FRS"</span>, <span class="at">x =</span> <span class="st">"NSSEC"</span>, <span class="at">y =</span> <span class="st">"Count"</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>()<span class="sc">+</span> <span class="co">#Flip the Axes, add a # in front of this line, to make the code in gray and you will see why we would better flip the axes at here</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03.QualitativeVariable_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>You can change the variables in ggplot() to make your own histogram chart for the variables you are interested in. You will learn more of visualisation methods in Week 5’s practical.</p>
</section>
<section id="correlation" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="correlation"><span class="header-section-number">4.1.2</span> Correlation</h3>
<p>As before, rather than relying upon an impressionistic view of the strength of the association between two variables, we can measure that association by calculating the relevant correlation coefficients.</p>
<p>To calculate the correlation between categorical data, we first use Chi-squared test to assess the independence between pairs of categorical variables, then we use Cramer’s V to measures the strength of association - the correlation coefficents in R.</p>
<p><strong>Pearson’s chi-squared test</strong> (χ2) is a statistical test applied to sets of categorical data to evaluate how likely it is that any observed difference between the sets arose by chance. If the p-value is low (typically &lt; 0.05), it suggests a significant association between the two variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(frs_data<span class="sc">$</span>health,frs_data<span class="sc">$</span>happy) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(frs_data$health, frs_data$happy): Chi-squared
approximation may be incorrect</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  frs_data$health and frs_data$happy
X-squared = 45594, df = 60, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>If you see a warning message of Chi-squared approximation may be incorrect. This is because some expected frequencies in one or more cells of the cross-tabulation (health * happy) are too low. The df means degrees of freedom and it relates to the size of the table and the number of categories in each variable. The most important message from the output is the estimated p-value, which shows as p-value &lt; 2.2e-16 (2.2 with 16 decimals move to the left, it is a very small number so written in scientific notation). P-value of the chi-squared test is far smaller than 0.05, so we can say the correlation is statistically significant.</p>
<p><strong>Cramér’s V</strong> is a measure of association for categorical (nominal or ordinal) data. It ranges from 0 (no association) to 1 (strong association). The main downside of using Cramer’s V is that no information is provided on whether the correlation is positive or negative. This is not a problem if the variable pair includes a nominal variable but represents an information loss if both variables being correlated are ordinal.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Install the 'vcd' package if not installed </span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span>(<span class="sc">!</span><span class="fu">require</span>(<span class="st">"vcd"</span>))   </span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"vcd"</span>, <span class="at">repos =</span> <span class="st">"https://cran.r-project.org"</span>, <span class="at">dependencies =</span> T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: vcd</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'vcd' was built under R version 4.5.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: grid</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)  </span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create the crosstable </span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>crosstab <span class="ot">&lt;-</span> <span class="fu">table</span>(frs_data<span class="sc">$</span>health, frs_data<span class="sc">$</span>happy)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Cramér's V </span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="fu">assocstats</span>(crosstab)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   X^2 df P(&gt; X^2)
Likelihood Ratio 54036 60        0
Pearson          45594 60        0

Phi-Coefficient   : NA 
Contingency Coeff.: 0.713 
Cramer's V        : 0.454 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co">#you can also directly calculate the association between variables</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">assocstats</span>(<span class="fu">table</span>(frs_data<span class="sc">$</span>health, frs_data<span class="sc">$</span>age_group))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                   X^2 df P(&gt; X^2)
Likelihood Ratio 26557 75        0
Pearson          23854 75        0

Phi-Coefficient   : NA 
Contingency Coeff.: 0.592 
Cramer's V        : 0.329 </code></pre>
</div>
</div>
<section id="q1-what-are-strongest-and-weakest-associations-health-status" class="level4 unnumbered" style="background-color: #FFFBCC; padding: 10px; border-radius: 5px; border: 1px solid #E1C948;">
<h4 class="unnumbered anchored" data-anchor-id="q1-what-are-strongest-and-weakest-associations-health-status">Q1: What are strongest and weakest associations health status?</h4>
<p><strong>Which of our selected person-level variables is most strongly/weakly correlated with an individual’s health status?</strong> Use the codes of Chi-square test and Cramer’s V to answer this question by completing Table 1.</p>
</section>
<p><strong>Table 1 Person-level correlations with health status</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Covariates</strong></td>
<td></td>
<td><strong>Correlation Coefficient</strong></td>
<td><strong>Statistical Significance</strong></td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td><em>Cramer’s V</em></td>
<td><em>p-value</em></td>
</tr>
<tr class="odd">
<td><em>health</em></td>
<td><em>age_group</em></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><em>health</em></td>
<td><em>highest_qual</em></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td><em>health</em></td>
<td><em>marital_status</em></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td><em>health</em></td>
<td><em>nssec</em></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="income-inequality-with-respect-to-gender-and-health-status" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="income-inequality-with-respect-to-gender-and-health-status"><span class="header-section-number">4.2</span> Income inequality with respect to gender and health status</h2>
<p>In this section, we will work with individual-level data (“FRS16-17_label.csv”) to explore income inequality with respect to gender and health status.</p>
<p>To explore income inequality, we need to work with a data set excluding dependent children. In addition, we look at individuals who are the representative persons of households. Therefore, we will select cases (or samples) that meet both conditions.</p>
<p>We want R to select persons only if they are the representative persons of households and they are not dependent children. The involved variables are <code>hrp</code> and <code>Dependent</code> for the categories “Household Reference Person” and “independent”, you can select the appropriate cases. We also want to exclude the health variable reported as “Not known”.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>frs_df <span class="ot">&lt;-</span> frs_data <span class="sc">%&gt;%</span> <span class="fu">filter</span>(hrp <span class="sc">==</span> <span class="st">"HRP"</span> <span class="sc">&amp;</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                                dependent <span class="sc">==</span> <span class="st">"Independent"</span> <span class="sc">&amp;</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                                health <span class="sc">!=</span> <span class="st">"Not known"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Then, we create a new numeric variable <code>Net_inc_perc</code> indicate net income per capita as our dependent variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>frs_df<span class="sc">$</span>Net_inc_pp <span class="ot">=</span> frs_df<span class="sc">$</span>hh_income_net <span class="sc">/</span> frs_df<span class="sc">$</span>hh_size  </span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(frs_df<span class="sc">$</span>Net_inc_pp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
-238160    9074   13347   15834   19136  864812 </code></pre>
</div>
</div>
<p>The distribution of the net household income per capita can be visualised by using <code>ggplot()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(frs_df, <span class="fu">aes</span>(<span class="at">x =</span> Net_inc_pp)) <span class="sc">+</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">250</span>, <span class="co">#A higher bins value means more, narrower bars, covers smaller range of value</span></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"black"</span>,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"skyblue"</span>,</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span>   <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Net_inc_pp"</span>, <span class="at">x =</span> <span class="st">"Value"</span>, <span class="at">y =</span>  <span class="st">"Frequency"</span>) <span class="sc">+</span>   <span class="fu">scale_x_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">label_comma</span>()) <span class="sc">+</span>  <span class="co"># Prevent scientific notation on the x axis</span></span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="03.QualitativeVariable_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our two qualitative independent variables “<code>sex</code>” and “<code>health</code>”. Let’s first know what they look like:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_df<span class="sc">$</span>sex) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Female   Male 
  7647   9180 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(frs_df<span class="sc">$</span>health)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      Bad      Fair      Good  Very Bad Very Good 
     1472      4253      6277       426      4399 </code></pre>
</div>
</div>
<p>Remember in the lecture, what we did in the Region long-term illness before we put the categorical variable Region into the regression model? Yes. First, make sure they are in factor type and Second, decide the reference category. Here, I will use Female and Very Bad health status as my base categories. You can decide what you wish to use. This time, I use the following codes to combine these two steps in one line.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>frs_df<span class="sc">$</span>sex <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(<span class="fu">as.factor</span>(frs_df<span class="sc">$</span>sex), <span class="st">"Female"</span>) </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>frs_df<span class="sc">$</span>health <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(<span class="fu">as.factor</span>(frs_df<span class="sc">$</span>health), <span class="st">"Very Bad"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Implement the regression model with the two qualitative independent variables.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>model_frs <span class="ot">&lt;-</span> <span class="fu">lm</span>(Net_inc_pp <span class="sc">~</span> sex <span class="sc">+</span> health, <span class="at">data =</span> frs_df) </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_frs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Net_inc_pp ~ sex + health, data = frs_df)

Residuals:
    Min      1Q  Median      3Q     Max 
-255133   -6547   -2213    3515  845673 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      12115.5      762.9  15.881  &lt; 2e-16 ***
sexMale           2091.2      240.6   8.691  &lt; 2e-16 ***
healthBad         -102.8      854.3  -0.120 0.904205    
healthFair        1051.3      789.0   1.332 0.182751    
healthGood        2766.0      777.4   3.558 0.000375 ***
healthVery Good   4931.8      787.8   6.260 3.95e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 15530 on 16821 degrees of freedom
Multiple R-squared:  0.01646,   Adjusted R-squared:  0.01616 
F-statistic: 56.29 on 5 and 16821 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Same as what you have learnt in Week 2, the code explanation:</p>
<p><strong><code>lm()</code> Function</strong>:</p>
<ul>
<li><code>lm()</code> stands for “linear model” and is used to fit a linear regression model in R.</li>
<li>The formula syntax <code>Net_inc_pp ~ Sex + health</code> specifies a relationship between:
<ul>
<li><strong>Dependent Variable</strong>: <code>Net_inc_pp</code>.</li>
<li><strong>Independent Variables</strong>: <code>Sex</code>, and <code>health</code>. The model is trained on the <code>data = frs_df</code> dataset.</li>
</ul></li>
</ul>
<p><strong>Storing the Model</strong>: The <code>model &lt;-</code> syntax stores the fitted model in an object called <code>model</code>.</p>
<p><code>summary(model)</code> provides a detailed output of the model’s results, including:</p>
<ul>
<li><strong>Coefficients</strong>: Estimates of the regression slopes (i.e., how each independent variable affects <code>Net_inc_pp</code>).</li>
<li><strong>Standard Errors</strong>: The variability of each coefficient estimate.</li>
<li><strong>t-values</strong> and <strong>p-values</strong>: Indicate the statistical significance of the effect of each independent (explanatory) variable.</li>
<li><strong>R-squared</strong> and <strong>Adjusted R-squared</strong>: Show how well the independent variables explain the variance in the dependent variable.</li>
<li><strong>F-statistic</strong>: Tests the overall significance of the model.</li>
</ul>
<p>The result can be formatted by:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom) </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tidy</span>(model_frs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  term            estimate std.error statistic  p.value
  &lt;chr&gt;              &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 (Intercept)       12116.      763.    15.9   2.21e-56
2 sexMale            2091.      241.     8.69  3.90e-18
3 healthBad          -103.      854.    -0.120 9.04e- 1
4 healthFair         1051.      789.     1.33  1.83e- 1
5 healthGood         2766.      777.     3.56  3.75e- 4
6 healthVery Good    4932.      788.     6.26  3.95e-10</code></pre>
</div>
</div>
<section id="q2.-income-inequality-by-gender-and-health" class="level3 unnumbered" style="background-color: #FFFBCC; padding: 10px; border-radius: 5px; border: 1px solid #E1C948;">
<h3 class="unnumbered anchored" data-anchor-id="q2.-income-inequality-by-gender-and-health">Q2. Income inequality by gender and health</h3>
<p><strong>What conclusions could be drawn in terms of income inequalities with respect to gender and health status? Also think about the statistical significance of these differences.</strong></p>
</section>
<p>The interpretation of this table is again similar to what you have learnt in Week 2, but you may find that R has automatically treated the categorical/qualitative variables <strong>sex</strong> and <strong>health</strong> as dummy variables. Each category gets a coefficient except the reference category set by <code>fct_relevel()</code>. That is why the output has <code>sexMale</code> but no <code>sexFemale</code>, and no <code>healthVery Bad</code>.</p>
<p>Each coefficient is therefore interpreted as a difference from the reference category, <strong>Female</strong> with <strong>Very Bad</strong> health, holding the other variable constant:</p>
<ul>
<li><p>The <strong>Intercept</strong> (<strong>£12,116</strong>) is the predicted net income per capita for the reference group: females with Very Bad health.</p></li>
<li><p>The association of <strong><code>sexMale</code></strong> is positive and statistically significant (<strong>+£2,091, p &lt; 0.001</strong>): men have £2,091 more net income per capita than women with the same health status, indicating a gender gap in income.</p></li>
<li><p>The associations of <strong><code>healthBad</code></strong> and <strong><code>healthFair</code></strong> are not statistically significant (<strong>p = 0.90</strong> and <strong>0.18</strong>): there is no evidence that their net income per capita differs from people in Very Bad health.</p></li>
<li><p>The associations of <strong><code>healthGood</code></strong> and <strong><code>healthVery Good</code></strong> are positive and statistically significant (<strong>+£2,766</strong> and <strong>+£4,932</strong>, both <strong>p &lt; 0.001</strong>): compared with people in Very Bad health, people in Good and Very Good health have £2,766 and £4,932 more net income per capita respectively, suggesting that income rises with better health.</p></li>
</ul>
<p>We then read R-squared and Adjusted R-squared to evaluate the model fit. Both are only around <strong>0.016</strong>, meaning <code>sex</code> and <code>health</code> together explain only 1.6% of the variation in <code>Net_inc_pp</code>. The model is therefore poor for prediction, and more variables (e.g.&nbsp;education level, occupation, age) would be needed to explain income better. Even so, the F-test is highly significant (<strong>p &lt; 2.2e-16</strong>), so the income gaps by gender and health identified above are real, even though they explain only a small part of why incomes differ.</p>
</section>
<section id="implementing-a-linear-regression-model-with-a-qualitative-independent-variable" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="implementing-a-linear-regression-model-with-a-qualitative-independent-variable"><span class="header-section-number">4.3</span> <strong>Implementing a linear regression model with a qualitative independent variable</strong></h2>
<p>To gain further practice on using linear regression models with qualitative variables as independent variables, we extend the model you created last week by adding the qualitative/categorical variable Region from the Census 2021 dataset. This allows us to answer <strong>Research Question 2: How does health vary across regions in England and Wales?</strong> You should already have the dataset <strong>EW_DistrictPercentages.csv</strong>; if not, you can download it from <a href="https://canvas.liverpool.ac.uk/courses/93312/pages/census-data?module_item_id=2727713">Canvas</a>. Please put the .csv file in your ‘/data/Census2021’ folder.</p>
<p>The practical is split into two main parts. The first focuses on implementing a linear regression model with a qualitative independent variable. <strong>Note that</strong> you need first to set the reference category (baseline) as the outcomes of the model reflects the <strong>differences</strong> between categories with the baseline. The second part focuses on prediction based the estimated linear regression model.</p>
<p>First we load the UK district-level census dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load data</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>LAcensus <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"../data/Census2021/EW_DistrictPercentages.csv"</span>) <span class="co"># Local authority level</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Using the district-level census dataset “<strong>EW__DistrictPercentages.csv</strong>”. the variable “Region” (labelled as Government Office Region) is used to explore regional inequality in health.</p>
<p>Familiarise yourself with the dataset by using the same codes as last week:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co">#view the data </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(LAcensus)  </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(LAcensus)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The names() function returns all the column names.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(LAcensus)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The dim() function simply returns the number of rows and number of columns.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(LAcensus) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 331 161</code></pre>
</div>
</div>
<p>There are 331 rows and 151 columns in the dataset. It would be very hard to scan through the data if we use so many variables altogether. Therefore, we can select several columns to tailor for this practical. You can of course include other variables you are interested in also by their names:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> LAcensus <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">c</span>(<span class="st">"pct_Longterm_sick_or_disabled"</span>,</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"pct_No_qualifications"</span>,</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"pct_Males"</span>,</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"pct_Higher_manager_prof"</span>,</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>                            <span class="st">"Region"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Simply descriptive of this new data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> pct_Longterm_sick_or_disabled pct_No_qualifications   pct_Males    
 Min.   :1.330                 Min.   : 6.61         Min.   :46.77  
 1st Qu.:2.865                 1st Qu.:15.06         1st Qu.:48.62  
 Median :3.810                 Median :17.63         Median :48.98  
 Mean   :4.013                 Mean   :17.90         Mean   :48.97  
 3rd Qu.:4.800                 3rd Qu.:20.41         3rd Qu.:49.30  
 Max.   :9.110                 Max.   :28.88         Max.   :55.02  
 pct_Higher_manager_prof    Region         
 Min.   : 5.49           Length:331        
 1st Qu.: 9.79           Class :character  
 Median :12.34           Mode  :character  
 Mean   :13.22                             
 3rd Qu.:15.80                             
 Max.   :39.68                             </code></pre>
</div>
</div>
<p>Now we can retrieve the “Region” column from the data frame by simply use <strong>df$Region</strong>. But what if we want to understand the data better, like the following questions?</p>
<section id="q3.-categories-of-region" class="level3 unnumbered" style="background-color: #FFFBCC; padding: 10px; border-radius: 5px; border: 1px solid #E1C948;">
<h3 class="unnumbered anchored" data-anchor-id="q3.-categories-of-region">Q3. Categories of Region</h3>
<p><strong>How many categories does the variable “Region” entail? How many local authority districts does each region include?</strong></p>
</section>
<p>Simply use the function table() would return you the answer.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>Region) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                    East            East Midlands                   London 
                      45                       35                       33 
              North East               North West               South East 
                      12                       39                       64 
              South West                    Wales            West Midlands 
                      30                       22                       30 
Yorkshire and The Humber 
                      21 </code></pre>
</div>
</div>
<p>The <code>table()</code> function tells us that this data frame contains 10 regions, and the number of LAs belongs to each region.</p>
<p>R can only include the categorical variables in the <strong>factor</strong> type, so we set the column <em>Region</em> in <code>factor()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Region<span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span>Region) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="include-the-categorical-variables-into-a-regression-model" class="level3" data-number="4.3.1">
<h3 data-number="4.3.1" class="anchored" data-anchor-id="include-the-categorical-variables-into-a-regression-model"><span class="header-section-number">4.3.1</span> <strong>Include the categorical variables into a regression model</strong></h3>
<p>We will continue with a very similar regression model fitted in last week that relates Percentages long-term illness (<em>pct_Long_term_sick_or_disabled</em>) to Percentages no-qualification (<em>pct_No_qualifications</em>), Percentage Males (<em>pct_Males</em>) and Percentages Higher Managerial or Professional occupation (<em>pct_Higher_manager_prof</em>).</p>
<p>Decide which region to be set as the baseline category. The principle is that if you want to compare the (average) long term illness outcome of Region A to those of other regions, Region A should be chosen as the baseline category. For example, if you want to compare the (average) long term illness outcome of London to rest of regions in the England and Wales, London should be selected as the baseline category.</p>
<p>Implement the regression model with the categorical variables - <em>Region</em> in our case. R will automatically handle the qualitative variable as dummy variables so you don’t need to concern any of that. But you need to let R knows which category of your qualitative variable is your reference category or the baseline. Here we will use London as our first go. <strong>Note:</strong> We choose London as the baseline category so the London region will be <u><strong>excluded</strong></u> in the independent variable list.</p>
<p>Therefore, first, we set London as the reference:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Region <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(df<span class="sc">$</span>Region,  <span class="st">"London"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Similar to last week, we build our linear regression model, but also include the <em>Region</em> variable into the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(pct_Longterm_sick_or_disabled <span class="sc">~</span> pct_Males <span class="sc">+</span> pct_No_qualifications <span class="sc">+</span> pct_Higher_manager_prof <span class="sc">+</span> Region, <span class="at">data =</span> df)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pct_Longterm_sick_or_disabled ~ pct_Males + pct_No_qualifications + 
    pct_Higher_manager_prof + Region, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.73799 -0.42623 -0.08528  0.41308  2.20676 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     7.615375   3.018425   2.523  0.01212 *  
pct_Males                      -0.167291   0.061638  -2.714  0.00701 ** 
pct_No_qualifications           0.251334   0.023179  10.843  &lt; 2e-16 ***
pct_Higher_manager_prof         0.007145   0.020244   0.353  0.72438    
RegionEast                     -0.760329   0.173260  -4.388 1.56e-05 ***
RegionEast Midlands            -0.254826   0.194419  -1.311  0.19090    
RegionNorth East                1.164153   0.260808   4.464 1.12e-05 ***
RegionNorth West                0.784897   0.192449   4.078 5.74e-05 ***
RegionSouth East               -0.328575   0.165728  -1.983  0.04827 *  
RegionSouth West                0.096484   0.214507   0.450  0.65317    
RegionWales                     1.382217   0.220643   6.264 1.21e-09 ***
RegionWest Midlands            -0.415570   0.196345  -2.117  0.03508 *  
RegionYorkshire and The Humber -0.118795   0.217473  -0.546  0.58528    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7086 on 318 degrees of freedom
Multiple R-squared:  0.7593,    Adjusted R-squared:  0.7502 
F-statistic:  83.6 on 12 and 318 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>You have already learnt how to interpret the output of regression model last week: <strong>Significance</strong> (p-value), <strong>Coefficient Estimates, and Model fit</strong> (R squared and Adjusted R-squared).</p>
<section id="q4.-regional-differences-compared-with-london" class="level4 unnumbered" style="background-color: #FFFBCC; padding: 10px; border-radius: 5px; border: 1px solid #E1C948;">
<h4 class="unnumbered anchored" data-anchor-id="q4.-regional-differences-compared-with-london">Q4. Regional differences compared with London</h4>
<p><strong>Relating back to this week’s lecture notes, indicate what regions have statistically significant differences in the percentage of long-term illness, compared to London?</strong></p>
</section>
<p>First, the <strong>Significance</strong> and the <strong>Coefficient Estimates</strong>. The p-values in the last column of the output table show that most of the independent variables are significant predictors of <code>pct_Longterm_sick_or_disabled</code>. All coefficients below are interpreted <strong>when the other predictors remain the same</strong>.</p>
<ul>
<li><p>The <strong>Intercept</strong> (<strong>7.62</strong>) is the predicted long-term sick/disabled rate for a <strong>London</strong> district (the reference category) when <code>pct_Males</code>, <code>pct_No_qualifications</code> and <code>pct_Higher_manager_prof</code> are all 0%. Since no real district has 0% males, we do not interpret this value directly; it is the baseline value to which the other coefficients are added when making predictions.</p></li>
<li><p><strong>Continuous variables.</strong> Similar to last week, <code>pct_No_qualifications</code> is significant at the &lt;0.001 level (three asterisks ***), indicating a highly statistically significant relationship. We are slightly less confident about <code>pct_Males</code>, which is significant at the &lt;0.01 level (two asterisks **). Their coefficient estimates tell us that:</p>
<ul>
<li><p>The association of <strong><code>pct_No_qualifications</code></strong> is positive and statistically significant (<strong>+0.25, p &lt; 0.001</strong>): each 1% increase in residents with no qualifications is associated with a 0.25% increase in the long-term sick/disabled rate, when the other predictors remain the same.</p></li>
<li><p>The association of <strong><code>pct_Males</code></strong> is negative and statistically significant (<strong>−0.17, p &lt; 0.01</strong>): each 1% increase in males is associated with a 0.17% decrease in the long-term sick/disabled rate, when the other predictors remain the same.</p></li>
<li><p>The association of <strong><code>pct_Higher_manager_prof</code></strong> is not statistically significant (<strong>p = 0.72</strong>).</p></li>
</ul></li>
<li><p><strong>Region dummy variables.</strong> R has created a dummy variable (the items starting with <code>Region</code>) for every region except the reference category, <strong>London</strong>. Each coefficient therefore shows how much higher (positive) or lower (negative) a region’s long-term sick/disabled rate is <strong>compared with London</strong>, when the other predictors remain the same:</p>
<ul>
<li><p><strong>Significant at the &lt;0.001 level (***):</strong> <code>RegionEast</code>, <code>RegionNorth East</code>, <code>RegionNorth West</code> and <code>RegionWales</code>. For example, the North East has a <strong>1.16%</strong> higher rate than London, and Wales a <strong>1.38%</strong> higher rate, while the East has a <strong>0.76%</strong> lower rate.</p></li>
<li><p><strong>Significant at the 0.05 level (*):</strong> <code>RegionSouth East</code> and <code>RegionWest Midlands</code>. This is weaker evidence than ***, so they are only mildly statistically significant.</p></li>
<li><p><strong>Not significant:</strong> <code>RegionEast Midlands</code>, <code>RegionSouth West</code> and <code>RegionYorkshire and The Humber</code>, meaning their rates are not significantly different from London’s.</p></li>
</ul>
<p>You can interpret the other regions in the same way using their coefficient estimates.</p>
<p><strong>Reminder</strong>: You <strong>cannot</strong> tell from this output whether North East and Wales, or any two regions other than London, are significantly different from each other, because each region’s coefficient only compares that region with London. To compare North East and Wales, set either of them as the reference category, using <code>df$Region &lt;- fct_relevel(df$Region, "North East")</code> or <code>df$Region &lt;- fct_relevel(df$Region, "Wales")</code>, and re-run the model.</p></li>
</ul>
<p>Last but not least, the <strong>Model Fit</strong>. R-squared (<strong>0.759</strong>) and Adjusted R-squared (<strong>0.750</strong>) are both around 0.75: the model explains 75.9% of the variation in the long-term sick/disabled rate across districts, or 75.0% after adjusting for the number of independent variables. Together, they suggest a strong fit of the model.</p>
</section>
<section id="change-the-baseline-category" class="level3" data-number="4.3.2">
<h3 data-number="4.3.2" class="anchored" data-anchor-id="change-the-baseline-category"><span class="header-section-number">4.3.2</span> <strong>Change the baseline category</strong></h3>
<p>If you would like to learn about differences in long-term illness between North East and other regions in the EW, you need to change the baseline category (from London) to the North East region (with variable name “Region_2”).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>Region <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(df<span class="sc">$</span>Region, <span class="st">"North West"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The regression model is specified again as follows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  pct_Longterm_sick_or_disabled <span class="sc">~</span> pct_Males <span class="sc">+</span> pct_No_qualifications <span class="sc">+</span> pct_Higher_manager_prof <span class="sc">+</span> Region,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pct_Longterm_sick_or_disabled ~ pct_Males + pct_No_qualifications + 
    pct_Higher_manager_prof + Region, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.73799 -0.42623 -0.08528  0.41308  2.20676 

Coefficients:
                                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                     8.400272   3.042017   2.761 0.006090 ** 
pct_Males                      -0.167291   0.061638  -2.714 0.007009 ** 
pct_No_qualifications           0.251334   0.023179  10.843  &lt; 2e-16 ***
pct_Higher_manager_prof         0.007145   0.020244   0.353 0.724376    
RegionLondon                   -0.784897   0.192449  -4.078 5.74e-05 ***
RegionEast                     -1.545226   0.158845  -9.728  &lt; 2e-16 ***
RegionEast Midlands            -1.039723   0.165225  -6.293 1.03e-09 ***
RegionNorth East                0.379256   0.235090   1.613 0.107685    
RegionSouth East               -1.113472   0.152463  -7.303 2.27e-12 ***
RegionSouth West               -0.688413   0.182460  -3.773 0.000192 ***
RegionWales                     0.597320   0.189607   3.150 0.001786 ** 
RegionWest Midlands            -1.200467   0.174076  -6.896 2.89e-11 ***
RegionYorkshire and The Humber -0.903692   0.191943  -4.708 3.74e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.7086 on 318 degrees of freedom
Multiple R-squared:  0.7593,    Adjusted R-squared:  0.7502 
F-statistic:  83.6 on 12 and 318 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Examining R-squared to measure the model fit. How robust is the new model? What % of the variance in the dependent variable has been explained?</p>
<p>Now, complete the following table.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Region names</th>
<th style="text-align: center;">Higher or lower than North West</th>
<th style="text-align: center;">Whether the difference is statistically significant (Yes or No)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">East Midlands</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">East</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">North East</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">South East</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">London</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">West Midlands</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Yorkshire and The Humber</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">Wales</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Check the answer at the end of this practical page.</p>
<p>Now it is very easy to use your model to estimate the results Y (dependent variable - <code>pct_Longterm_sick_or_disabled</code> ) by setting all the input independent variable X (<code>pct_Males</code> <code>pct_No_qualifications</code> and <code>pct_Higher_manager_prof</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>obj_London <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Males =</span> <span class="fl">49.7</span>,</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_No_qualifications =</span> <span class="fl">24.3</span>,</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Higher_manager_prof =</span> <span class="fl">14.7</span>,</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Region =</span> <span class="st">"London"</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>obj_WM <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Males =</span> <span class="fl">49.8</span>,</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_No_qualifications =</span> <span class="fl">23.3</span>,</span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Higher_manager_prof =</span> <span class="fl">11.2</span>,</span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Region =</span> <span class="st">"West Midlands"</span></span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb73-13"><a href="#cb73-13" aria-hidden="true" tabindex="-1"></a>obj_NE <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb73-14"><a href="#cb73-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Males =</span> <span class="fl">49.8</span>,</span>
<span id="cb73-15"><a href="#cb73-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_No_qualifications =</span> <span class="fl">23.3</span>,</span>
<span id="cb73-16"><a href="#cb73-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Higher_manager_prof =</span> <span class="fl">11.2</span>,</span>
<span id="cb73-17"><a href="#cb73-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">Region =</span> <span class="st">"North East"</span></span>
<span id="cb73-18"><a href="#cb73-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb73-19"><a href="#cb73-19" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb73-20"><a href="#cb73-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-21"><a href="#cb73-21" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, obj_London) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
5.513467 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, obj_WM) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
4.804829 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, obj_NE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
6.384552 </code></pre>
</div>
</div>
</section>
<section id="recode-the-region-variable-and-explore-regional-inequality-in-health" class="level3" data-number="4.3.3">
<h3 data-number="4.3.3" class="anchored" data-anchor-id="recode-the-region-variable-and-explore-regional-inequality-in-health"><span class="header-section-number">4.3.3</span> Recode the Region variable and explore regional inequality in health</h3>
<p>In many real-world studies, we might not be interested in health inequality across all regions. For example, in this case study, we are interested in health inequality between <em>London</em>, <em>South, North, Midland and Wales</em>. We can achieve this by re-grouping regions in England and Wales based on the variable “Region”. That said, we need to have a new grouping of regions as follows:</p>
<table class="caption-top table">
<tbody>
<tr class="odd">
<td><strong>Original region labels</strong></td>
<td><strong>New region labels</strong></td>
</tr>
<tr class="even">
<td>East Midlands</td>
<td>Midlands</td>
</tr>
<tr class="odd">
<td>East</td>
<td>South</td>
</tr>
<tr class="even">
<td>London</td>
<td>London</td>
</tr>
<tr class="odd">
<td>North East</td>
<td>North</td>
</tr>
<tr class="even">
<td>North West</td>
<td>North</td>
</tr>
<tr class="odd">
<td>South East</td>
<td>South</td>
</tr>
<tr class="even">
<td>South West</td>
<td>South</td>
</tr>
<tr class="odd">
<td>West Midlands</td>
<td>Midlands</td>
</tr>
<tr class="even">
<td>Yorkshire and The Humber</td>
<td>North</td>
</tr>
<tr class="odd">
<td>Wales</td>
<td>Wales</td>
</tr>
</tbody>
</table>
<p>Here we use mutate() function in R to make it happen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">New_region_label =</span> <span class="fu">fct_collapse</span>(</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>      Region,</span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">North =</span> <span class="fu">c</span>(<span class="st">"North East"</span>, <span class="st">"North West"</span>, <span class="st">"Yorkshire and The Humber"</span>),</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">Midlands =</span> <span class="fu">c</span>(<span class="st">"East Midlands"</span>, <span class="st">"West Midlands"</span>),</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">South =</span> <span class="fu">c</span>(<span class="st">"East"</span>, <span class="st">"South East"</span>, <span class="st">"South West"</span>),</span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">London =</span> <span class="st">"London"</span>,</span>
<span id="cb79-9"><a href="#cb79-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">Wales =</span> <span class="st">"Wales"</span></span>
<span id="cb79-10"><a href="#cb79-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb79-11"><a href="#cb79-11" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This code may look a bit complex. You can simply type ?mutate in your console. Now in your right hand Help window, the R studio offers you the explanation of the mutate function. This is a common way you can use R studio to help you learn what the function ca<code>ate()</code> creates new columns that are functions of existing variables. Therefore, the <code>df %&gt;% mutate()</code> means add a new column into the current dataframe <code>df</code>; the <code>New_region_label</code> in the <code>mutate()</code> function indicates the name of this new column is <code>New_region_label</code>. The right side of the <code>New_region_label =</code> indicates the value we want to assign to the <code>New_region_label</code> in each row.</p>
<p>The right side of <code>New_region_label</code> is</p>
<p><code>fct_collapse(Region, North = c("North East", "North West", "Yorkshire and The Humber"), Midlands = c("East Midlands", "West Midlands"), South = c("East", "South East", "South West"), London = "London", Wales = "Wales")</code></p>
<p>By using the code, the <code>fct_collapse()</code> function recodes or group each value in the <code>Region</code> column into one of the broader categories: “London”, “South”, “North”,“Midlands” or “Wales”. Specifically, it takes the existing factor levels in <code>Region</code> and collapses multiple detailed regions into fewer, aggregated groups. For example, regions such as <em>“North East”</em>, <em>“North West”</em>, and <em>“Yorkshire and The Humber”</em> are all grouped under <strong>“North”</strong>, while <em>“East Midlands”</em> and <em>“West Midlands”</em> are combined into <strong>“Midlands”</strong>, and so on.</p>
<p>Now we use the same way to examine our new column <code>New_region_label</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>New_region_label)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   North   London    South Midlands    Wales 
      72       33      139       65       22 </code></pre>
</div>
</div>
<p>Comparing with the <code>Region_label</code>, we now can see the mutate worked:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>df[,<span class="fu">c</span>(<span class="st">"Region"</span>,<span class="st">"New_region_label"</span>)]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now you will have a new qualitative variable named <code>New_region_label</code> in which the UK is divided into five regions: London, South, North, Midlands and Wales.</p>
<p><em>Based on the newly generated qualitative variable</em> <code>New_region_label</code>, we can now build our new linear regression model. Don’t forget:</p>
<p>(1) R need to deal with the categorical variables in regression model in the factor type;</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(df<span class="sc">$</span>New_region_label)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "factor"</code></pre>
</div>
</div>
<p>The <code>class()</code> returns the type of the variable. The <code>New_region_label</code> is already a factor variable. If not, we need to convert it by the <code>as.factor()</code>, as we used above.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>New_region_label <span class="ot">=</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>New_region_label)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>(1) Let R know which region you want to use as the baseline category. Here I will use London again, but of course you can choose other regions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>New_region_label <span class="ot">&lt;-</span> <span class="fu">fct_relevel</span>(df<span class="sc">$</span>New_region_label, <span class="st">"London"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The linear regression window is set up below. This time we include <code>New_region_label</code> rather than <code>Region_label</code> as the region variable:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>  pct_Longterm_sick_or_disabled <span class="sc">~</span> pct_Males <span class="sc">+</span> pct_No_qualifications <span class="sc">+</span> pct_Higher_manager_prof <span class="sc">+</span> New_region_label,</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = pct_Longterm_sick_or_disabled ~ pct_Males + pct_No_qualifications + 
    pct_Higher_manager_prof + New_region_label, data = df)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.83271 -0.48362 -0.06293  0.40581  2.11961 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)               9.98363    3.20535   3.115  0.00201 ** 
pct_Males                -0.18418    0.06585  -2.797  0.00547 ** 
pct_No_qualifications     0.20143    0.02257   8.924  &lt; 2e-16 ***
pct_Higher_manager_prof  -0.03410    0.01986  -1.718  0.08684 .  
New_region_labelNorth     0.47416    0.18706   2.535  0.01172 *  
New_region_labelSouth    -0.50635    0.16433  -3.081  0.00224 ** 
New_region_labelMidlands -0.41031    0.18517  -2.216  0.02740 *  
New_region_labelWales     1.25183    0.23431   5.343 1.73e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.76 on 323 degrees of freedom
Multiple R-squared:  0.7188,    Adjusted R-squared:  0.7127 
F-statistic:   118 on 7 and 323 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<section id="q5.-london-vs-north-and-south-vs-wales" class="level4 unnumbered" style="background-color: #FFFBCC; padding: 10px; border-radius: 5px; border: 1px solid #E1C948;">
<h4 class="unnumbered anchored" data-anchor-id="q5.-london-vs-north-and-south-vs-wales">Q5. London vs North, and South vs Wales</h4>
<p><strong>Are there statistically significant differences in the percentage of people with long-term sick/disable between London and North, and between South and Wales, controlling for other variables? What conclusions could be drawn in terms of regional differences in health outcome?</strong></p>
</section>
</section>
</section>
<section id="predictions-using-fitted-regression-model" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="predictions-using-fitted-regression-model"><span class="header-section-number">4.4</span> Predictions using fitted regression model</h2>
<p><strong>Write down the % long term sick or disabled regression model with the new region label categorical variables.</strong></p>
<p>Relating to this week’s lecture, the % <code>pct_Longterm_sick_or_disabled</code> is equal to:</p>
<p><strong>[write down the model]</strong></p>
<section id="q6.-predicting-long-term-illness-in-wales-and-london" class="level3 unnumbered" style="background-color: #FFFBCC; padding: 10px; border-radius: 5px; border: 1px solid #E1C948;">
<h3 class="unnumbered anchored" data-anchor-id="q6.-predicting-long-term-illness-in-wales-and-london">Q6. Predicting long-term illness in Wales and London</h3>
<p><strong>Now imagine that the values of variables <em>pct_Males, pct_No_qualifications, and pct_Higher_manager_prof</em> are 49, 23 and 11, respectively, what would the percentage of persons with long-term sick/disable in Wales and London be?</strong></p>
</section>
<p>Check the answer at the end of this practical page.</p>
</section>
<section id="answers-to-the-questions" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="answers-to-the-questions"><span class="header-section-number">4.5</span> <strong>Answers to the Questions</strong></h2>
<section id="q1-associations-with-health-status" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="q1-associations-with-health-status"><span class="header-section-number">4.5.1</span> Q1 associations with health status</h3>
<p>Using the Chi-squared test and Cramér’s V, Table 1 can be completed as follows:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Covariates</strong></th>
<th style="text-align: center;"></th>
<th style="text-align: center;"><strong>Cramér’s V</strong></th>
<th style="text-align: center;"><strong>p-value</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><em>health</em></td>
<td style="text-align: center;"><em>age_group</em></td>
<td style="text-align: center;">0.329</td>
<td style="text-align: center;">&lt; 0.001</td>
</tr>
<tr class="even">
<td style="text-align: center;"><em>health</em></td>
<td style="text-align: center;"><em>highest_qual</em></td>
<td style="text-align: center;">0.287</td>
<td style="text-align: center;">&lt; 0.001</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><em>health</em></td>
<td style="text-align: center;"><em>nssec</em></td>
<td style="text-align: center;">0.280</td>
<td style="text-align: center;">&lt; 0.001</td>
</tr>
<tr class="even">
<td style="text-align: center;"><em>health</em></td>
<td style="text-align: center;"><em>marital_status</em></td>
<td style="text-align: center;">0.229</td>
<td style="text-align: center;">&lt; 0.001</td>
</tr>
</tbody>
</table>
<p>All four associations are statistically significant (p &lt; 0.001). <strong>Age group</strong> has the strongest association with health status (Cramér’s V = 0.329), and <strong>marital status</strong> the weakest (0.229). Remember that Cramér’s V tells us the strength of an association, but not its direction.</p>
</section>
<section id="q2-income-inequality-by-gender-and-health-status" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="q2-income-inequality-by-gender-and-health-status"><span class="header-section-number">4.5.2</span> Q2: income inequality by gender and health status</h3>
<ul>
<li><strong>Gender:</strong> men have £2,091 more net income per capita than women with the same health status (p &lt; 0.001), indicating a significant gender gap in income.</li>
<li><strong>Health:</strong> compared with people in Very Bad health, people in Good and Very Good health have £2,766 and £4,932 more net income per capita respectively (both p &lt; 0.001). The differences for Bad and Fair health are not statistically significant.</li>
<li><strong>Model fit:</strong> sex and health explain only 1.6% of the variation in income (R² = 0.016), so other factors matter much more. However, the income gaps by gender and health are statistically significant.</li>
</ul>
</section>
<section id="q3-categories-of-region" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="q3-categories-of-region"><span class="header-section-number">4.5.3</span> Q3: categories of Region</h3>
<p><code>table(df$Region)</code> shows <strong>10 regions</strong> with 331 local authority districts in total: East (45), East Midlands (35), London (33), North East (12), North West (39), South East (64), South West (30), Wales (22), West Midlands (30) and Yorkshire and The Humber (21).</p>
</section>
<section id="q4-regions-that-differ-significantly-from-london" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="q4-regions-that-differ-significantly-from-london"><span class="header-section-number">4.5.4</span> Q4: regions that differ significantly from London</h3>
<p>Holding the other predictors constant, compared with London:</p>
<ul>
<li><strong>Significantly higher:</strong> Wales (+1.38%), North East (+1.16%) and North West (+0.78%), all p &lt; 0.001.</li>
<li><strong>Significantly lower:</strong> East (−0.76%, p &lt; 0.001), West Midlands (−0.42%, p &lt; 0.05) and South East (−0.33%, p &lt; 0.05).</li>
<li><strong>Not significantly different:</strong> East Midlands, South West, and Yorkshire and The Humber.</li>
</ul>
</section>
<section id="changing-the-baseline-to-north-west" class="level3" data-number="4.5.5">
<h3 data-number="4.5.5" class="anchored" data-anchor-id="changing-the-baseline-to-north-west"><span class="header-section-number">4.5.5</span> Changing the baseline to North West</h3>
<p>R-squared (0.759) and Adjusted R-squared (0.750) are <strong>exactly the same</strong> as in the model with London as the baseline. Changing the reference category does not change the model fit; it only changes which comparisons the Region coefficients show.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Region names</th>
<th style="text-align: center;">Higher or lower than North West</th>
<th style="text-align: center;">Statistically significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">East Midlands</td>
<td style="text-align: center;">Lower (−1.04%)</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">East</td>
<td style="text-align: center;">Lower (−1.55%)</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">North East</td>
<td style="text-align: center;">Higher (+0.38%)</td>
<td style="text-align: center;">No (p = 0.11)</td>
</tr>
<tr class="even">
<td style="text-align: center;">South East</td>
<td style="text-align: center;">Lower (−1.11%)</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">South West</td>
<td style="text-align: center;">Lower (−0.69%)</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">London</td>
<td style="text-align: center;">Lower (−0.78%)</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">West Midlands</td>
<td style="text-align: center;">Lower (−1.20%)</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: center;">Yorkshire and The Humber</td>
<td style="text-align: center;">Lower (−0.90%)</td>
<td style="text-align: center;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Wales</td>
<td style="text-align: center;">Higher (+0.60%)</td>
<td style="text-align: center;">Yes</td>
</tr>
</tbody>
</table>
<p>Note that London is 0.78% lower than North West, which is the same size as the North West coefficient in the London-baseline model (+0.78%), with the opposite sign.</p>
</section>
<section id="q5-london-vs-north-and-south-vs-wales" class="level3" data-number="4.5.6">
<h3 data-number="4.5.6" class="anchored" data-anchor-id="q5-london-vs-north-and-south-vs-wales"><span class="header-section-number">4.5.6</span> Q5: London vs North, and South vs Wales</h3>
<ul>
<li><p><strong>London vs North:</strong> yes. With London as the baseline, the North has a 0.47% higher long-term sick/disabled rate than London (p = 0.012), when the other predictors remain the same.</p></li>
<li><p><strong>South vs Wales:</strong> this <strong>cannot</strong> be answered from <code>model2</code>, because both South and Wales are compared only with London. To test it, set one of them as the reference category, e.g.&nbsp;<code>df$New_region_label &lt;- fct_relevel(df$New_region_label, "South")</code>, and re-run the model. Doing so shows that Wales has a 1.76% higher rate than the South (p &lt; 0.001).</p></li>
<li><p><strong>Conclusion:</strong> after controlling for sex, qualifications and occupation, <code>model2</code> tells us how each region compares with <strong>London</strong>: Wales (+1.25%) and the North (+0.47%) have significantly higher long-term sick/disabled rates than London, while the South (−0.51%) and the Midlands (−0.41%) have significantly lower rates. This suggests clear regional inequalities in health across England and Wales.</p>
<p><strong>Reminder</strong>: these conclusions are all <em>relative to London</em>. Although the coefficients suggest an ordering (e.g.&nbsp;Wales appears higher than the North, and the North higher than the South), <code>model2</code> <strong>cannot</strong> tell us whether the differences between two non-London regions are statistically significant. To test any such comparison, the model must be <strong>re-built</strong> with one of those regions as the reference category, as we did above for South vs Wales.</p></li>
</ul>
</section>
<section id="the-written-down-model-and-q6" class="level3" data-number="4.5.7">
<h3 data-number="4.5.7" class="anchored" data-anchor-id="the-written-down-model-and-q6"><span class="header-section-number">4.5.7</span> The written-down model and Q6</h3>
<p>The model of the new region label is: pct_Longterm_sick_or_disabled (%) = 9.98+ (-0.1842)* pct_Males (%) + 0.2014 * pct_No_qualifications (%) + (-0.0341) * pct_Higher_manager_prof + (0.4742) * North + (-0.5063) * South + (-0.4103) * Midlands + 1.2518 * Wales, where North, South, Midlands and Wales are dummy variables (1 if the district is in that region, 0 otherwise). London is the reference category, so all four dummies are 0 for London. Note that <code>pct_Higher_manager_prof</code> is not statistically significant at the 0.05 level (p = 0.087).</p>
<p>If <code>pct_Males</code>, <code>pct_No_qualifications</code> and <code>pct_Higher_manager_prof</code> are 49, 23 and 11:</p>
<ul>
<li><strong>Wales</strong> (Wales = 1, other dummies = 0): <code>9.98 + (-0.1842)*49 + 0.2014*23 + (-0.0341)*11 + 1.2518*1</code></li>
<li><strong>London</strong> (all dummies = 0): <code>9.98 + (-0.1842)*49 + 0.2014*23 + (-0.0341)*11</code></li>
</ul>
<p>You can paste these directly into your RStudio Console to get the results. You can also make a new object and use <code>predict()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>obj_Wales <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Males =</span> <span class="dv">49</span>,</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_No_qualifications =</span> <span class="dv">23</span>,</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Higher_manager_prof =</span> <span class="dv">11</span>,</span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">New_region_label =</span> <span class="st">"Wales"</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>obj_London <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Males =</span> <span class="dv">49</span>,</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_No_qualifications =</span> <span class="dv">23</span>,</span>
<span id="cb89-11"><a href="#cb89-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">pct_Higher_manager_prof =</span> <span class="dv">11</span>,</span>
<span id="cb89-12"><a href="#cb89-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">New_region_label =</span> <span class="st">"London"</span></span>
<span id="cb89-13"><a href="#cb89-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb89-14"><a href="#cb89-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-15"><a href="#cb89-15" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model2, obj_Wales)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
6.468668 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model2, obj_London)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
5.216834 </code></pre>
</div>
</div>
<p><strong>Therefore, the predicted percentages of persons with long-term illness in Wales and London are 6.47% and 5.22% respectively.</strong> The difference (1.25%) is exactly the Wales coefficient, because the two districts have the same values for all the other predictors. If you got the right answers, congratulations: you can now use a regression model to make predictions!</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/gdsl-ul\.github\.io\/stats");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../labs/02.MultipleLinear.html" class="pagination-link" aria-label="Lab: Correlation, Single, and Multiple Linear Regression">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lab: Correlation, Single, and Multiple Linear Regression</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../labs/04.LogisticRegression.html" class="pagination-link" aria-label="Lab: Logistic Regression">
        <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Lab: Logistic Regression</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Exploring the Social World - Quantitative Block: Statistics by Gabriele Filomena and Zi Ye.</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/GDSL-UL/stats/edit/main/labs/03.QualitativeVariable.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>This book was built with <a href="https://quarto.org/">Quarto</a>.</p>
</div>
  </div>
</footer>




</body></html>